# Generated by Django 5.0.7 on 2024-07-25 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите курс', max_length=100, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, help_text='Укажите описание', null=True, verbose_name='Описание')),
                ('preview_course', models.ImageField(blank=True, help_text='Укажите превью', null=True, upload_to='materials/preview_course', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите урок', max_length=100, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, help_text='Укажите описание', null=True, verbose_name='Описание')),
                ('preview_lesson', models.ImageField(blank=True, help_text='Укажите превью', null=True, upload_to='materials/preview_lesson', verbose_name='Превью')),
                ('link_to_video', models.CharField(blank=True, help_text='Укажите ссылку', max_length=100, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.course', verbose_name='Название курса')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
